# Docker Compose file for local development environment

version: '3.8'

services:
  backend:
    build: .
    container_name: pixelo-backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=pixelo_local_db
      - POSTGRES_HOST=db
      - SSL_MODE=disable

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app/backend

  db:
    image: postgres:15-alpine
    container_name: pixelo-db
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=pixelo_local_db
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localuser -d pixelo_local_db"]
      interval: 5s
      timeout: 5s
      retries: 5